//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTRODUCTION
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public System.DateTime create_date { get; set; }
        public int create_user { get; set; }
        public Nullable<int> update_user { get; set; }
        public string image { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
