//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class PROPERTY
    {
        public HttpPostedFileBase AvatarUpload { get; set; }
        public IEnumerable<HttpPostedFileBase> UpImages { get; set; }

    }
}
